services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Berlin
      HOSTNAME: ubuntu-server
      BESZEL_HUB_URL: ${BESZEL_HUB_URL:-http://127.0.0.1:8090}
      BESZEL_TOKEN: ${BESZEL_TOKEN:-changeme}
      KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM3DJlGiLLrIN/i0OGdkzZYU4pm2T7iYvX2u+tn7Onyq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host:ro
    privileged: true
